version: 2.1
orbs:
  accuknox-scan: accuknox-scan/accuknox-test-scan@dev:1.119
workflows:
  accuknox:
    jobs:
      - accuknox-scan/sast:
          INPUT_SOFT_FAIL: false
          SKIP_SONAR_SCAN: true
      - print-env

jobs:
  print-env:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Environment Variables
          command: printenv