version: 2.1
orbs:
  accuknox-scan: accuknox-scan/accuknox-test-scan@dev:1.117
workflows:
  accuknox:
    jobs:
      - accuknox-scan/sast:
          INPUT_SOFT_FAIL: false
          SKIP_SONAR_SCAN: false