name: AccuKnox Secret Scan Workflow


on:
  push:
    branches:
      - secret

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: AccuKnox Secret Scan
        uses: accuknox/secret-scan-action@v1.0.1
        with:
          # secret_scan_type: s3
          # bucket_name: safeer-accuknox-test
          # aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          # secret_scan_type: huggingface
          # huggingface_token: ${{ secrets.HUGGINGFACE_TOKEN }}
          # dataset: samsum

          token: ${{ secrets.ACCUKNOX_TOKEN_SECRET }}
          tenant_id: 5050
          label: "SecretScan"
          endpoint:  "cspm.demo.accuknox.com"
          fail: true
          use_extended_ruleset: false
