name: Opengrep Test

on:
  push:
    branches:
      - opengrep-test
  pull_request:
    branches:
      - opengrep-test

env:
  INPUT_SOFT_FAIL: "false"

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenGrep
        uses: safeer-accuknox/opengrep-action@1.0.1
        with:
          ACCUKNOX_ENDPOINT: "cspm.dev.accuknox.com"
          ACCUKNOX_TENANT: "${{ secrets.DEV_TENANT_ID }}"
          ACCUKNOX_TOKEN: "${{ secrets.DEV_TOKEN }}"
          ACCUKNOX_LABEL: "SPOC"