name: Opengrep Test

on:
  push:
    branches:
      - opengrep-test
  pull_request:
    branches:
      - opengrep-test

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenGrep
        uses: safeer-accuknox/opengrep-action@1.0.8
        with:
          accuknox_endpoint: "cspm.stage.accuknox.com"
          accuknox_tenant: "${{ secrets.STAGE_TENANT_ID }}"
          accuknox_token: "${{ secrets.STAGE_TOKEN }}"
          accuknox_label: "SPOC"
          input_soft_fail: "true"