name: Opengrep Test

on:
  push:
    branches:
      - opengrep-test
  pull_request:
    branches:
      - opengrep-test

env:
  INPUT_SOFT_FAIL: "false"

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OpenGrep Test
        env:
          PIPELINE_ID: "${{ github.run_id }}"
          JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          set +e  # Allow commands to fail without stopping the script
          docker run --rm -v "$PWD:/app" \
            -e REPOSITORY_URL="$REPOSITORY_URL" \
            -e COMMIT_SHA="$COMMIT_SHA" \
            -e COMMIT_REF="$COMMIT_REF" \
            -e PIPELINE_ID="$PIPELINE_ID" \
            -e JOB_URL="$JOB_URL" \
            safeeraccuknox/demo:opengreptest-1.2
          echo "OPENGREP_EXIT_CODE=$?" >> $GITHUB_ENV
          echo "OPENGREP_EXIT_CODE_V1=$OPENGREP_EXIT_CODE"

      - name: Push report to CSPM panel
        shell: bash
        env:
          END_POINT: "cspm.dev.accuknox.com"
          TENANT_ID: "${{ secrets.DEV_TENANT_ID }}"
          TOKEN: "${{ secrets.DEV_TOKEN }}"
          LABEL: "SPOC"
        run: |
          set +e
          cat results.json
          curl --silent --show-error --fail --location \
            --request POST "https://${END_POINT}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=SG&label_id=${LABEL}&save_to_s3=true" \
            --header "Tenant-Id: ${TENANT_ID}" \
            --header "Authorization: Bearer ${TOKEN}" \
            --form 'file=@"results.json"'
          echo "AK_EXIT_CODE=$?" >> $GITHUB_ENV
          echo "AK_EXIT_CODE_V1=$AK_EXIT_CODE"

      - name: Fail pipeline if scan fails
        run: |
          FINAL_EXIT_CODE=0

          if [ "$OPENGREP_EXIT_CODE" -ne 0 ] || [ "$AK_EXIT_CODE" -ne 0 ]; then
            FINAL_EXIT_CODE=$OPENGREP_EXIT_CODE
            if [ "$OPENGREP_EXIT_CODE" -eq 0 ]; then
              FINAL_EXIT_CODE=$AK_EXIT_CODE
            fi
          fi

          echo "OPENGREP_EXIT_CODE_V2=$OPENGREP_EXIT_CODE"
          echo "AK_EXIT_CODE_V2=$AK_EXIT_CODE"
          echo "FINAL_EXIT_CODE=$FINAL_EXIT_CODE"

          if [ "$FINAL_EXIT_CODE" -ne 0 ]; then
            if [ "$INPUT_SOFT_FAIL" = "true" ]; then
              echo "Scan failed, but soft fail is enabled. Continuing..."
            else
              echo "Scan failed and soft fail is disabled. Exiting with failure."
              exit 1
            fi
          else
            echo "Scan completed successfully."
          fi
